# Generated by Django 3.2.6 on 2021-09-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motelcasino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkin',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='checkout',
            field=models.DateTimeField(blank=True),
        ),
    ]
